spring:
  application:
    name: livestream-user-provider
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:livestream-db-sharding.yaml
    hikari:
      pool-name: livestream-user-pool
      minimum-idle: 150
      maximum-pool-size: 300
      connection-timeout: 4000
      max-lifetime: 60000
      idle-timeout: 60000
  data:
    redis:
      port: 6379
      host: localhost
      password: root
      lettuce:
        pool:
          min-idle: 10
          max-active: 50
          max-idle: 20
      database: 2
dubbo:
  application:
    architecture: ${spring.application.name}
  registry:
    address: nacos://127.0.0.1:8848?namespace=livestream-test&username=live&password=live
  protocol:
    name: dubbo
    port: 9091